import type { AccountType } from '@/shared/types';
import { isIconName } from '@/src/components/ui/icon-registry';
import type { IconName } from '@/src/components/ui/icon-registry';

// String type aliases for icon name strings stored in DB
export type MaterialIconName = string;
export type IoniconName = string;

export const LEGACY_ICON_MAP: Record<string, string> = {
  "accessibility-outline": "user",
  "account-group-outline": "user-group",
  "account-group-outline-dup": "user-multiple",
  "account-outline": "user",
  "alarm-outline": "alarm-clock",
  "alarm": "alarm-clock",
  "alert-circle": "alert-circle",
  "alert": "alert-circle",
  "airplane-outline": "airplane",
  "airplane": "airplane",
  "analytics-outline": "chart-line-data",
  "archive-outline": "archive",
  "arrow-down-circle-outline": "arrow-down",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "arrow-up-circle-outline": "arrow-up",
  "bag-outline": "shopping-bag",
  "bandage-outline": "bandage",
  "bandage": "bandage",
  "bar-chart-outline": "bar-chart",
  "barbell-outline": "dumbbell",
  "basket-outline": "shopping-basket",
  "bed-outline": "bed",
  "beer-outline": "beer",
  "bicycle-outline": "bike",
  "bike": "bike",
  "boat-outline": "sailboat-coastal",
  "boat": "boat",
  "book-open-page-variant-outline": "book-open",
  "book-outline": "book-open",
  "briefcase-outline": "briefcase",
  "build-outline": "wrench",
  "bus-outline": "bus",
  "bus": "bus",
  "business-outline": "building",
  "cafe-outline": "coffee",
  "calculator-outline": "bar-chart",
  "calculator": "bar-chart",
  "calendar-outline": "calendar",
  "calendar": "calendar",
  "car-outline": "car",
  "card-account-details-outline": "credit-card",
  "card-outline": "credit-card",
  "card": "credit-card",
  "cash-outline": "cash",
  "cash": "cash",
  "cellphone": "smartphone",
  "chat-outline": "chat",
  "chatbubbles-outline": "chat",
  "check-circle-outline": "checkmark-circle",
  "check-circle": "checkmark-circle",
  "check-decagram-outline": "checkmark-circle",
  "check": "check",
  "chevron-right": "arrow-right",
  "clock-outline": "clock",
  "close-circle-outline": "cancel-circle",
  "close-circle": "cancel-circle",
  "cloud-outline": "cloud",
  "cog-outline": "settings",
  "compass-outline": "compass",
  "content-cut": "scissor",
  "cpu-64-bit": "cpu",
  "creation": "sparkles",
  "cut-outline": "scissor",
  "desktop-outline": "computer",
  "diamond-outline": "diamond",
  "diamond-stone": "diamond",
  "document-text-outline": "file",
  "domain": "building",
  "dots-horizontal": "more-horizontal",
  "dots-vertical": "more-horizontal",
  "download-outline": "arrow-down",
  "earth": "earth",
  "egg-outline": "egg",
  "ellipsis-horizontal-outline": "more-horizontal",
  "emoticon-happy-outline": "smile",
  "fast-food-outline": "hamburger",
  "file-document-outline": "file",
  "film-outline": "film",
  "filmstrip": "film",
  "fitness-outline": "heart-pulse",
  "flame-outline": "flame",
  "flame": "flame",
  "flash-outline": "flash",
  "folder-outline": "folder",
  "food-apple": "apple",
  "football-outline": "football",
  "football": "football",
  "game-controller-outline": "gamepad",
  "gamepad-variant-outline": "gamepad",
  "gift-outline": "gift",
  "glass-wine": "drink",
  "globe-outline": "earth",
  "golf-outline": "golf-ball",
  "golf": "golf-ball",
  "grid-outline": "grid",
  "grid": "grid",
  "hamburger": "hamburger",
  "hammer-outline": "hammer",
  "hammer": "hammer",
  "happy-outline": "smile",
  "hardware-chip-outline": "cpu",
  "heart-circle-outline": "heart",
  "heart-outline": "heart",
  "heart-pulse": "heart-pulse",
  "home-outline": "home",
  "human-greeting": "smile",
  "human": "user",
  "ice-cream-outline": "ice-cream",
  "id-card-outline": "credit-card",
  "information-outline": "information-circle",
  "information": "information-circle",
  "key-outline": "key",
  "key": "key",
  "laptop-outline": "laptop",
  "laptop": "laptop",
  "layers-outline": "layers",
  "leaf-outline": "leaf",
  "leaf": "leaf",
  "library-outline": "library",
  "lightbulb-on-outline": "bulb",
  "lightning-bolt": "flash",
  "locate-outline": "map-pin",
  "lock-closed-outline": "lock",
  "lock-outline": "lock",
  "lock": "lock",
  "magnify": "search",
  "map-outline": "maps",
  "medical-bag": "bandage",
  "medkit-outline": "bandage",
  "monitor": "computer",
  "moon-outline": "moon",
  "moon-waning-crescent": "moon",
  "musical-notes-outline": "music-note",
  "nutrition-outline": "apple",
  "palette-outline": "paint-brush",
  "paw-outline": "cat",
  "paw": "cat",
  "pencil-outline": "pencil",
  "people-outline": "user-group",
  "person-outline": "user",
  "phone-portrait-outline": "smartphone",
  "pie-chart-outline": "pie-chart",
  "pizza-outline": "pizza",
  "pizza": "pizza",
  "plus-circle-outline": "chart-bar-increasing",
  "plus": "chart-bar-increasing",
  "print-outline": "printer",
  "printer-outline": "printer",
  "pulse-outline": "pulse",
  "receipt-outline": "receipt-text",
  "receipt-text-outline": "receipt-text",
  "refresh-outline": "refresh",
  "refresh": "refresh",
  "repeat-outline": "repeat",
  "restaurant-outline": "fork",
  "ribbon-outline": "ribbon",
  "rocket-launch-outline": "rocket",
  "rocket-outline": "rocket",
  "server-outline": "server-stack",
  "server": "server-stack",
  "share-outline": "share",
  "shield-check-outline": "shield",
  "shield-checkmark-outline": "shield",
  "shirt-outline": "t-shirt",
  "shopping-outline": "shopping-bag",
  "silverware-fork-knife": "fork",
  "sparkles-outline": "sparkles",
  "speedometer-outline": "dashboard-speed",
  "star-outline": "star",
  "stats-chart-outline": "bar-chart",
  "subway-outline": "metro",
  "sunny-outline": "sun",
  "swap-horizontal": "repeat",
  "sync": "refresh",
  "tablet-portrait-outline": "tablet",
  "tag-multiple-outline": "tag",
  "tag-outline": "tag",
  "thermometer-outline": "thermometer",
  "train-outline": "train",
  "trash-can-outline": "delete",
  "trending-up-outline": "chart-up",
  "trophy-outline": "award",
  "tshirt-crew-outline": "t-shirt",
  "umbrella-outline": "umbrella",
  "walk-outline": "walking",
  "water-outline": "droplets",
  "weight-lifter": "dumbbell",
  "wifi-outline": "wifi",
  "wine-outline": "drink",
};

/**
 * A stored icon string (category / account, from the database) as a registry name, mapping
 * pre-Hugeicons names through LEGACY_ICON_MAP. Returns the fallback for anything unrecognised.
 */
export function resolveIcon(icon: string | null | undefined, fallback: IconName): IconName {
  if (!icon) return fallback;
  const key = LEGACY_ICON_MAP[icon] || icon;
  return isIconName(key) ? key : fallback;
}

export const ACCOUNT_TYPE_ICON_MAP: Record<AccountType, IconName> = {
  cash: 'cash',
  bank: 'building',
  savings: 'piggy-bank',
  credit_card: 'credit-card',
  investment: 'chart-line-data',
  loan: 'receipt-text',
  ewallet: 'wallet',
};

export function resolveAccountTypeIcon(accountType: AccountType | null | undefined): IconName {
  if (!accountType) return 'building';
  return ACCOUNT_TYPE_ICON_MAP[accountType] ?? 'building';
}
