#!/usr/bin/env node
/**
 * Builds design/icons/glyphs.ts from design/icons/icon-map.json.
 *
 * The map gives each of our icon names a Phosphor glyph. The set is used in
 * two line weights, as the reference does: pictograms in `regular` (a 1.5pt
 * line at 24pt) and the few bare marks that are controls (close, tick, more)
 * in `bold` (2.25pt), written `"x": "x@bold"`. A pictogram also
 * gets its solid drawing; a bold mark has none and stays as it is.
 *
 * For every entry this copies the drawings (one SVG path each, on a 256 unit
 * grid) out of `@phosphor-icons/core`, so the app ships only the icons it
 * names and needs no icon library at runtime.
 *
 *   node scripts/generate-icons.js     # after editing icon-map.json
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ICONS = path.join(ROOT, 'node_modules/@phosphor-icons/core/assets');
const MAP = path.join(ROOT, 'design/icons/icon-map.json');
const OUT = path.join(ROOT, 'design/icons/glyphs.ts');

const pathOf = (weight, glyph) => {
  const file = path.join(ICONS, weight, weight === 'regular' ? `${glyph}.svg` : `${glyph}-${weight}.svg`);
  if (!fs.existsSync(file)) return null;
  const svg = fs.readFileSync(file, 'utf8');
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  const shapes = (svg.match(/<(?!\/?svg|path)[a-z]+/g) ?? []).length;
  if (!paths.length || shapes || !svg.includes('viewBox="0 0 256 256"')) throw new Error(`Unexpected SVG shape: ${file}`);
  return paths.join(' ');
};

const map = JSON.parse(fs.readFileSync(MAP, 'utf8'));
const missing = [];
const lines = [];
for (const name of Object.keys(map).sort()) {
  const [glyph, weight = 'regular'] = map[name].split('@');
  if (weight !== 'regular' && weight !== 'bold') throw new Error(`${name}: the weight is "regular" or "bold", not "${weight}"`);
  const line = pathOf(weight, glyph);
  const fill = weight === 'bold' ? line : pathOf('fill', glyph);
  if (!line || !fill) { missing.push(`${name} -> ${map[name]}`); continue; }
  lines.push(`  '${name}': { line: '${line}', fill: '${fill}' },`);
}
if (missing.length) {
  console.error(`No Phosphor glyph for:\n  ${missing.join('\n  ')}`);
  process.exit(1);
}

fs.writeFileSync(OUT, `// Generated by scripts/generate-icons.js from icon-map.json. Do not edit by hand.
// Glyphs: Phosphor Icons (MIT), https://phosphoricons.com

/** The side of the square grid every glyph is drawn on. */
export const GLYPH_GRID = 256;

/** One SVG path per style. */
export type Glyph = { line: string; fill: string };

export const GLYPHS = {
${lines.join('\n')}
} as const satisfies Record<string, Glyph>;

export type GlyphName = keyof typeof GLYPHS;
`);
console.log(`Wrote ${lines.length} icons to ${path.relative(ROOT, OUT)}`);
