#!/usr/bin/env node
/**
 * Builds design/icons/glyphs.ts from design/icons/icon-map.json.
 *
 * The map gives each of our icon names a Remix Icon glyph. For every entry
 * this copies the outline and the solid drawing (one SVG path each, on a 24
 * unit grid) out of the `remixicon` package, so the app ships only the icons
 * it names and needs no icon library at runtime.
 *
 *   node scripts/generate-icons.js     # after editing icon-map.json
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ICONS = path.join(ROOT, 'node_modules/remixicon/icons');
const MAP = path.join(ROOT, 'design/icons/icon-map.json');
const OUT = path.join(ROOT, 'design/icons/glyphs.ts');

const files = new Map();
for (const group of fs.readdirSync(ICONS)) {
  const dir = path.join(ICONS, group);
  if (!fs.statSync(dir).isDirectory()) continue;
  for (const file of fs.readdirSync(dir)) files.set(file, path.join(dir, file));
}

const pathOf = (file) => {
  const svg = fs.readFileSync(file, 'utf8');
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  if (!paths.length || !svg.includes('viewBox="0 0 24 24"')) throw new Error(`Unexpected SVG shape: ${file}`);
  return paths.join(' ');
};

const map = JSON.parse(fs.readFileSync(MAP, 'utf8'));
const missing = [];
const lines = [];
for (const name of Object.keys(map).sort()) {
  const glyph = map[name];
  // A few glyphs (text-editing ones) exist in a single style, named without a suffix.
  const line = files.get(`${glyph}-line.svg`) ?? files.get(`${glyph}.svg`);
  const fill = files.get(`${glyph}-fill.svg`) ?? line;
  if (!line) { missing.push(`${name} -> ${glyph}`); continue; }
  lines.push(`  '${name}': { line: '${pathOf(line)}', fill: '${pathOf(fill)}' },`);
}
if (missing.length) {
  console.error(`No Remix glyph for:\n  ${missing.join('\n  ')}`);
  process.exit(1);
}

fs.writeFileSync(OUT, `// Generated by scripts/generate-icons.js from icon-map.json. Do not edit by hand.
// Glyphs: Remix Icon (Apache-2.0), https://remixicon.com

/** One SVG path per style, drawn on a 24 by 24 grid. */
export type Glyph = { line: string; fill: string };

export const GLYPHS = {
${lines.join('\n')}
} as const satisfies Record<string, Glyph>;

export type GlyphName = keyof typeof GLYPHS;
`);
console.log(`Wrote ${lines.length} icons to ${path.relative(ROOT, OUT)}`);
