// The app's UI icon vocabulary — Hugeicons (the app's single icon pack).
// Semantic names (e.g. MagnifyingGlassIcon) map to the Hugeicons glyph used
// everywhere, so swapping a glyph app-wide is a one-line change here.
// Category & account icons stored in the database resolve via src/utils/icons.ts.

export {
  AlarmClockIcon as AlarmIcon,
  AndroidIcon as AndroidLogoIcon,
  Apple01Icon as AppleLogoIcon,
  ArrowDownLeft01Icon as ArrowDownLeftIcon,
  ArrowRight02Icon as ArrowRightIcon,
  ArrowUpRight01Icon as ArrowUpRightIcon,
  RefreshIcon as ArrowsClockwiseIcon,
  ArrowDataTransferHorizontalIcon as ArrowsLeftRightIcon,
  BankIcon as BankIcon,
  Notification01Icon as BellIcon,
  NotificationSquareIcon as BellRingingIcon,
  NotificationOff01Icon as BellSlashIcon,
  Briefcase01Icon as BriefcaseIcon,
  Calculator01Icon as CalculatorIcon,
  Calendar03Icon as CalendarBlankIcon,
  Car01Icon as CarIcon,
  ArrowDown01Icon as CaretDownIcon,
  ArrowLeft01Icon as CaretLeftIcon,
  ArrowRight01Icon as CaretRightIcon,
  BarChartIcon as ChartBarIcon,
  PieChart01Icon as ChartPieSliceIcon,
  CheckmarkCircle02Icon as CheckCircleIcon,
  Tick02Icon as CheckIcon,
  ContrastIcon as CircleHalfIcon,
  Clock01Icon as ClockIcon,
  CloudUploadIcon as CloudArrowUpIcon,
  CloudIcon as CloudIcon,
  Coffee01Icon as CoffeeIcon,
  Coins01Icon as CoinsIcon,
  Copy01Icon as CopyIcon,
  MoreHorizontalIcon as DotsThreeIcon,
  MoreVerticalIcon as DotsThreeVerticalIcon,
  Download01Icon as DownloadSimpleIcon,
  Share01Icon as ExportIcon,
  File01Icon as FileTextIcon,
  FlaskConicalIcon as FlaskIcon,
  FolderOpenIcon as FolderOpenIcon,
  Restaurant01Icon as ForkKnifeIcon,
  Settings01Icon as GearIcon,
  Globe02Icon as GlobeIcon,
  MoneyExchange01Icon as HandCoinsIcon,
  Cursor01Icon as HandSwipeLeftIcon,
  TouchInteraction01Icon as HandTapIcon,
  Home01Icon as HouseIcon,
  // Tab bar set — one rounded family (house with arched door, folded wallet,
  // framed bars, rounded gear) chosen together so the four read as a set.
  Home05Icon as TabHomeIcon,
  Wallet03Icon as TabAccountsIcon,
  Analytics01Icon as TabAnalyticsIcon,
  Settings02Icon as TabSettingsIcon,
  InformationCircleIcon as InfoIcon,
  FlashIcon as LightningIcon,
  LockPasswordIcon as LockKeyIcon,
  Search01Icon as MagnifyingGlassIcon,
  Moon02Icon as MoonIcon,
  PaintBoardIcon as PaletteIcon,
  PinCodeIcon as PasswordIcon,
  PencilEdit01Icon as PencilSimpleIcon,
  PiggyBankIcon as PiggyBankIcon,
  PlusSignIcon as PlusIcon,
  Invoice03Icon as ReceiptIcon,
  CheckmarkBadge01Icon as SealCheckIcon,
  ShieldKeyIcon as ShieldCheckIcon,
  ShoppingBag01Icon as ShoppingBagIcon,
  FilterHorizontalIcon as SlidersHorizontalIcon,
  SparklesIcon as SparkleIcon,
  GridViewIcon as SquaresFourIcon,
  Sun03Icon as SunIcon,
  Tag01Icon as TagIcon,
  TranslateIcon as TranslateIcon,
  Delete02Icon as TrashIcon,
  ArrowDown01Icon as TrendDownIcon,
  ArrowUp01Icon as TrendUpIcon,
  UserCircleIcon as UserCircleIcon,
  UserIcon as UserIcon,
  UserGroupIcon as UsersIcon,
  Wallet01Icon as WalletIcon,
  AlertCircleIcon as WarningCircleIcon,
  Alert02Icon as WarningIcon,
  CancelCircleIcon as XCircleIcon,
  Cancel01Icon as XIcon,
} from '@hugeicons/core-free-icons';
