import type { IconSvgElement } from '@hugeicons/react-native';
import {
  Airplane01Icon,
  AlarmClockIcon,
  Alert02Icon,
  AlertCircleIcon,
  Analytics01Icon,
  AndroidIcon,
  Apple01Icon,
  ArchiveIcon,
  ArrowDataTransferHorizontalIcon,
  ArrowDown01Icon,
  ArrowDownLeft01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  Award01Icon,
  BandageIcon,
  BankIcon,
  BarChartIcon,
  BatteryCharging01Icon,
  BedIcon,
  BeerIcon,
  BikeIcon,
  BoatIcon,
  BookOpen01Icon,
  Briefcase01Icon,
  Building03Icon,
  BulbIcon,
  Bus01Icon,
  Calculator01Icon,
  Calendar01Icon,
  Calendar03Icon,
  Call02Icon,
  Camera01Icon,
  Cancel01Icon,
  CancelCircleIcon,
  Car01Icon,
  Cash01Icon,
  CatIcon,
  ChartBarIncreasingIcon,
  ChartLineData01Icon,
  ChartUpIcon,
  Chat01Icon,
  CheckIcon,
  CheckmarkBadge01Icon,
  CheckmarkCircle01Icon,
  CheckmarkCircle02Icon,
  Clock01Icon,
  CloudIcon,
  CloudUploadIcon,
  Coffee01Icon,
  Coins01Icon,
  Coins02Icon,
  Compass01Icon,
  ComputerIcon,
  ContrastIcon,
  Copy01Icon,
  CpuIcon,
  CreditCardIcon,
  CrownIcon,
  Cursor01Icon,
  DashboardSpeed01Icon,
  Delete01Icon,
  Delete02Icon,
  Diamond01Icon,
  Download01Icon,
  DrinkIcon,
  DropletsIcon,
  Dumbbell01Icon,
  EarthIcon,
  EggIcon,
  File01Icon,
  Film01Icon,
  FilterHorizontalIcon,
  FilterIcon,
  FireIcon,
  Flag01Icon,
  Flame,
  FlameIcon,
  FlashIcon,
  FlaskConicalIcon,
  Folder01Icon,
  FolderOpenIcon,
  FootballIcon,
  ForkIcon,
  GamepadIcon,
  GiftIcon,
  Globe02Icon,
  GolfBallIcon,
  GridIcon,
  GridViewIcon,
  HamburgerIcon,
  HammerIcon,
  HandshakeIcon,
  HeadsetIcon,
  HeartIcon,
  HeartPulseIcon,
  HelpCircleIcon,
  Home01Icon,
  Home05Icon,
  IceCream01Icon,
  InboxIcon,
  InfinityCircleIcon,
  InformationCircleIcon,
  Invoice03Icon,
  Key01Icon,
  LaptopIcon,
  Layers01Icon,
  Leaf01Icon,
  LibraryIcon,
  LockIcon,
  LockPasswordIcon,
  Logout01Icon,
  Mail01Icon,
  MapPinIcon,
  MapsIcon,
  MetroIcon,
  Money01Icon,
  MoneyExchange01Icon,
  Moon01Icon,
  Moon02Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MusicNote01Icon,
  NoteIcon,
  Notification01Icon,
  NotificationOff01Icon,
  NotificationSquareIcon,
  PaintBoardIcon,
  PaintBrush01Icon,
  PencilEdit01Icon,
  PencilIcon,
  PieChart01Icon,
  PiggyBankIcon,
  PinCodeIcon,
  Pizza01Icon,
  PlusSignIcon,
  PrinterIcon,
  Pulse01Icon,
  ReceiptTextIcon,
  RefreshIcon,
  ReloadIcon,
  RepeatIcon,
  Restaurant01Icon,
  RibbonIcon,
  Rocket01Icon,
  SailboatCoastalIcon,
  SchoolIcon,
  ScissorIcon,
  Search,
  Search01Icon,
  ServerStack01Icon,
  Settings01Icon,
  Settings02Icon,
  Share01Icon,
  Shield01Icon,
  ShieldKeyIcon,
  ShoppingBag01Icon,
  ShoppingBasket01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SmileIcon,
  SortingDownIcon,
  SparklesIcon,
  StarIcon,
  Sun01Icon,
  Sun03Icon,
  TShirtIcon,
  Tablet01Icon,
  Tag01Icon,
  ThermometerIcon,
  Tick02Icon,
  TouchInteraction01Icon,
  Train01Icon,
  TranslateIcon,
  TrendingUpDownIcon,
  UmbrellaIcon,
  Upload01Icon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
  WalkingIcon,
  Wallet01Icon,
  Wallet03Icon,
  Wallet05Icon,
  Wifi01Icon,
  Wrench01Icon,
  ZapIcon,
} from '@hugeicons/core-free-icons';
import { BackspaceIcon } from './custom-icons';

/**
 * Every icon the app draws, by name — the only place a glyph is chosen. Swap an icon app-wide by
 * changing its entry here; nothing else imports an icon pack. Render with <Icon name="…" />.
 *
 * Two kinds of names share the record:
 *  - Stored names (kebab-case nouns like 'shopping-cart') are saved in users' databases as category
 *    and account icons. Never rename or remove one; point it at a different glyph instead.
 *  - Interface names describe a role in the UI ('chevron-right', 'trash', 'tab-home').
 */
export const HUGEICONS = {
  // Stored names (category / account icons) — persisted, never rename.
  'airplane': Airplane01Icon,
  'alarm-clock': AlarmClockIcon,
  'alert-circle': AlertCircleIcon,
  'apple': Apple01Icon,
  'archive': ArchiveIcon,
  'arrow-down': ArrowDown01Icon,
  'arrow-left': ArrowLeft01Icon,
  'arrow-right': ArrowRight01Icon,
  'arrow-up': ArrowUp01Icon,
  'award': Award01Icon,
  'bandage': BandageIcon,
  'bar-chart': BarChartIcon,
  'bed': BedIcon,
  'beer': BeerIcon,
  'bike': BikeIcon,
  'boat': BoatIcon,
  'book-open': BookOpen01Icon,
  'briefcase': Briefcase01Icon,
  'building': Building03Icon,
  'bulb': BulbIcon,
  'bus': Bus01Icon,
  'calendar': Calendar01Icon,
  'camera': Camera01Icon,
  'cancel-circle': CancelCircleIcon,
  'car': Car01Icon,
  'cash': Cash01Icon,
  'cat': CatIcon,
  'chart-bar-increasing': ChartBarIncreasingIcon,
  'chart-line-data': ChartLineData01Icon,
  'chart-up': ChartUpIcon,
  'check': CheckIcon,
  'checkmark-circle': CheckmarkCircle01Icon,
  'clock': Clock01Icon,
  'cloud': CloudIcon,
  'coffee': Coffee01Icon,
  'computer': ComputerIcon,
  'compass': Compass01Icon,
  'cpu': CpuIcon,
  'credit-card': CreditCardIcon,
  'dashboard-speed': DashboardSpeed01Icon,
  'delete': Delete01Icon,
  'diamond': Diamond01Icon,
  'drink': DrinkIcon,
  'droplets': DropletsIcon,
  'dumbbell': Dumbbell01Icon,
  'earth': EarthIcon,
  'egg': EggIcon,
  'file': File01Icon,
  'film': Film01Icon,
  'fire': FireIcon,
  'flag': Flag01Icon,
  'flame': FlameIcon,
  'flash': FlashIcon,
  'folder': Folder01Icon,
  'football': FootballIcon,
  'fork': ForkIcon,
  'gamepad': GamepadIcon,
  'gift': GiftIcon,
  'grid': GridIcon,
  'golf-ball': GolfBallIcon,
  'hamburger': HamburgerIcon,
  'hammer': HammerIcon,
  'headset': HeadsetIcon,
  'heart': HeartIcon,
  'heart-pulse': HeartPulseIcon,
  'home': Home01Icon,
  'ice-cream': IceCream01Icon,
  'information-circle': InformationCircleIcon,
  'key': Key01Icon,
  'laptop': LaptopIcon,
  'layers': Layers01Icon,
  'leaf': Leaf01Icon,
  'library': LibraryIcon,
  'lock': LockIcon,
  'map-pin': MapPinIcon,
  'maps': MapsIcon,
  'metro': MetroIcon,
  'moon': Moon01Icon,
  'more-horizontal': MoreHorizontalIcon,
  'music-note': MusicNote01Icon,
  'paint-brush': PaintBrush01Icon,
  'pencil': PencilIcon,
  'pie-chart': PieChart01Icon,
  'pizza': Pizza01Icon,
  'printer': PrinterIcon,
  'pulse': Pulse01Icon,
  'receipt-text': ReceiptTextIcon,
  'refresh': RefreshIcon,
  'repeat': RepeatIcon,
  'ribbon': RibbonIcon,
  'rocket': Rocket01Icon,
  'sailboat-coastal': SailboatCoastalIcon,
  'scissor': ScissorIcon,
  'school': SchoolIcon,
  'search': Search01Icon,
  'server-stack': ServerStack01Icon,
  'settings': Settings01Icon,
  'share': Share01Icon,
  'shield': Shield01Icon,
  'shopping-bag': ShoppingBag01Icon,
  'shopping-basket': ShoppingBasket01Icon,
  'shopping-cart': ShoppingCart01Icon,
  'smartphone': SmartPhone01Icon,
  'smile': SmileIcon,
  'sparkles': SparklesIcon,
  'star': StarIcon,
  'sun': Sun01Icon,
  'tablet': Tablet01Icon,
  'tag': Tag01Icon,
  'thermometer': ThermometerIcon,
  'train': Train01Icon,
  't-shirt': TShirtIcon,
  'umbrella': UmbrellaIcon,
  'user-group': UserGroupIcon,
  'user': UserIcon,
  'user-multiple': UserMultipleIcon,
  'walking': WalkingIcon,
  'wifi': Wifi01Icon,
  'wrench': Wrench01Icon,
  'chat': Chat01Icon,
  'wallet': Wallet01Icon,
  'piggy-bank': PiggyBankIcon,

  // Interface names.
  'alarm': AlarmClockIcon,
  'android-logo': AndroidIcon,
  'apple-logo': Apple01Icon,
  'arrow-down-left': ArrowDownLeft01Icon,
  'arrow-forward': ArrowRight02Icon,
  'arrow-up-right': ArrowUpRight01Icon,
  'arrows-clockwise': RefreshIcon,
  'arrows-left-right': ArrowDataTransferHorizontalIcon,
  'backspace': BackspaceIcon,
  'bank': BankIcon,
  'battery-charging': BatteryCharging01Icon,
  'bell': Notification01Icon,
  'bell-ringing': NotificationSquareIcon,
  'bell-slash': NotificationOff01Icon,
  'calculator': Calculator01Icon,
  'calendar-blank': Calendar03Icon,
  'call': Call02Icon,
  'chart-bar': BarChartIcon,
  'chart-pie': PieChart01Icon,
  'check-circle': CheckmarkCircle02Icon,
  'chevron-down': ArrowDown01Icon,
  'chevron-left': ArrowLeft01Icon,
  'chevron-right': ArrowRight01Icon,
  'circle-half': ContrastIcon,
  'cloud-arrow-up': CloudUploadIcon,
  'coins': Coins01Icon,
  'coins-stack': Coins02Icon,
  'copy': Copy01Icon,
  'crown': CrownIcon,
  'dots-three': MoreHorizontalIcon,
  'dots-three-vertical': MoreVerticalIcon,
  'download-simple': Download01Icon,
  'export': Share01Icon,
  'file-text': File01Icon,
  'filter': FilterIcon,
  'flask': FlaskConicalIcon,
  'folder-open': FolderOpenIcon,
  'fork-knife': Restaurant01Icon,
  'gear': Settings01Icon,
  'globe': Globe02Icon,
  'hand-coins': MoneyExchange01Icon,
  'hand-swipe-left': Cursor01Icon,
  'hand-tap': TouchInteraction01Icon,
  'handshake': HandshakeIcon,
  'house': Home01Icon,
  'inbox': InboxIcon,
  'infinity-circle': InfinityCircleIcon,
  'info': InformationCircleIcon,
  'question': HelpCircleIcon,
  'lightning': FlashIcon,
  'lock-key': LockPasswordIcon,
  'logout': Logout01Icon,
  'mail': Mail01Icon,
  'money': Money01Icon,
  'note': NoteIcon,
  'palette': PaintBoardIcon,
  'password': PinCodeIcon,
  'pencil-simple': PencilEdit01Icon,
  'plus': PlusSignIcon,
  'receipt': Invoice03Icon,
  'reload': ReloadIcon,
  'seal-check': CheckmarkBadge01Icon,
  'search-simple': Search,
  'shield-check': ShieldKeyIcon,
  'sliders-horizontal': FilterHorizontalIcon,
  'sorting-down': SortingDownIcon,
  'sparkle': SparklesIcon,
  'squares-four': GridViewIcon,
  'streak': Flame,
  'tab-accounts': Wallet03Icon,
  'tab-analytics': Analytics01Icon,
  'tab-home': Home05Icon,
  'tab-settings': Settings02Icon,
  'theme-dark': Moon02Icon,
  'theme-light': Sun03Icon,
  'tick': Tick02Icon,
  'translate': TranslateIcon,
  'trash': Delete02Icon,
  'trend-down': ArrowDown01Icon,
  'trend-up': ArrowUp01Icon,
  'trending-up-down': TrendingUpDownIcon,
  'upload': Upload01Icon,
  'user-circle': UserCircleIcon,
  'users': UserGroupIcon,
  'wallet-stack': Wallet05Icon,
  'warning': Alert02Icon,
  'warning-circle': AlertCircleIcon,
  'x': Cancel01Icon,
  'x-circle': CancelCircleIcon,
  'zap': ZapIcon,
} as const satisfies Record<string, IconSvgElement>;

export type IconName = keyof typeof HUGEICONS;

/** Icon families the <Icon> component can draw from. Add a family as a full or partial name → glyph
 *  map; names it lacks fall back to Hugeicons, so a family can be adopted one icon at a time. */
export const ICON_FAMILIES = {
  hugeicons: HUGEICONS,
} as const satisfies Record<string, Partial<Record<IconName, IconSvgElement>>>;

export type IconFamily = keyof typeof ICON_FAMILIES;
export const DEFAULT_ICON_FAMILY: IconFamily = 'hugeicons';

/** The stored names, in the order the icon picker offers them. */
export const STORED_ICON_NAMES = ['airplane', 'alarm-clock', 'alert-circle', 'apple', 'archive', 'arrow-down', 'arrow-left', 'arrow-right', 'arrow-up', 'award', 'bandage', 'bar-chart', 'bed', 'beer', 'bike', 'boat', 'book-open', 'briefcase', 'building', 'bulb', 'bus', 'calendar', 'camera', 'cancel-circle', 'car', 'cash', 'cat', 'chart-bar-increasing', 'chart-line-data', 'chart-up', 'check', 'checkmark-circle', 'clock', 'cloud', 'coffee', 'computer', 'compass', 'cpu', 'credit-card', 'dashboard-speed', 'delete', 'diamond', 'drink', 'droplets', 'dumbbell', 'earth', 'egg', 'file', 'film', 'fire', 'flag', 'flame', 'flash', 'folder', 'football', 'fork', 'gamepad', 'gift', 'grid', 'golf-ball', 'hamburger', 'hammer', 'headset', 'heart', 'heart-pulse', 'home', 'ice-cream', 'information-circle', 'key', 'laptop', 'layers', 'leaf', 'library', 'lock', 'map-pin', 'maps', 'metro', 'moon', 'more-horizontal', 'music-note', 'paint-brush', 'pencil', 'pie-chart', 'pizza', 'printer', 'pulse', 'receipt-text', 'refresh', 'repeat', 'ribbon', 'rocket', 'sailboat-coastal', 'scissor', 'school', 'search', 'server-stack', 'settings', 'share', 'shield', 'shopping-bag', 'shopping-basket', 'shopping-cart', 'smartphone', 'smile', 'sparkles', 'star', 'sun', 'tablet', 'tag', 'thermometer', 'train', 't-shirt', 'umbrella', 'user-group', 'user', 'user-multiple', 'walking', 'wifi', 'wrench', 'chat', 'wallet', 'piggy-bank'] as const satisfies readonly IconName[];

export const isIconName = (value: unknown): value is IconName => typeof value === 'string' && value in HUGEICONS;
